import type { Metadata, Viewport } from 'next';
import '../styles/globals.css';
import { Providers } from '@/components/Providers';
import { AppShell } from '@/components/AppShell';



import { APP_URL } from '@/lib/env';
export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: 'DeFier · Know what your capital is actually earning',
  description: 'Onchain capital intelligence on Base. True LP P&L, LP versus holding, exposure, tokenized stocks, and an assistant that answers with the engine\'s own figures.',
  openGraph: {
    title: 'DeFier',
    description: 'Did providing liquidity actually beat holding? Find out from your onchain history.',
    url: APP_URL,
    siteName: 'DeFier',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'DeFier',
    description: 'Did providing liquidity actually beat holding?',
  },
  /**
   * Without this the app had no tab icon at all. The mark was being served at
   * /icon.png the whole time and nothing in the page ever pointed at it: those
   * routes are plain route handlers, not Next's icon file convention, so no
   * link tag was emitted and the browser fell back to asking for /favicon.ico,
   * which answered 404.
   */
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '64x64', type: 'image/png' },
      { url: '/icon.png', sizes: '1024x1024', type: 'image/png' },
    ],
    shortcut: '/favicon.ico',
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  other: {
    // Base App reads this to render the app as an embed rather than a plain link.
    'fc:miniapp': JSON.stringify({
      version: '1',
      imageUrl: `${APP_URL}/embed.png`,   // 3:2, the shape an embed actually is
      button: {
        title: 'Analyse a wallet',
        action: { type: 'launch_miniapp', name: 'DeFier', url: APP_URL, splashBackgroundColor: '#08090C' },
      },
    }),
  },
};
export const viewport: Viewport = { width: 'device-width', initialScale: 1, maximumScale: 5, themeColor: '#08090C' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* OnchainKit ships Tailwind v4 CSS; loading it as a plain stylesheet keeps it
            out of our Tailwind v3 pipeline. Generated by scripts/copy-onchainkit-styles.mjs. */}
        <link rel="stylesheet" href="/onchainkit.css" />
      </head>
      <body>
        {/* Structured data, so a crawler or an agent that never reads a line of
            our prose still knows what this is, who made it, and that it costs
            nothing to try. JSON-LD rather than microdata because it is one
            block to keep correct instead of attributes scattered through the
            markup that drift the first time the layout changes. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'WebApplication',
            name: 'DeFier',
            url: APP_URL,
            applicationCategory: 'FinanceApplication',
            operatingSystem: 'Any',
            description: 'Onchain capital intelligence on Base. Reconstructs every liquidity position a wallet has opened, values each amount at the price of the day it happened, and reports whether providing liquidity actually beat holding the same tokens.',
            offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
            isAccessibleForFree: true,
            featureList: [
              'True profit and loss on liquidity positions, valued day by day',
              'Liquidity versus holding the same tokens',
              'Lending and borrowing positions with the protocol\u2019s own health factor',
              'Tokenized stock holdings on Base',
            ],
          }) }}
        />
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
