import type { Metadata, Viewport } from 'next';
import '../styles/globals.css';
import { Providers } from '@/components/Providers';
import { AppShell } from '@/components/AppShell';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://defier-alpha.vercel.app';

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: 'DeFier · Know what your capital is actually earning',
  description: 'Onchain capital intelligence on Base. True LP P&L, LP versus holding, exposure, tokenized stocks, and an assistant that answers with the engine\'s own figures.',
  openGraph: {
    title: 'DeFier',
    description: 'Did providing liquidity actually beat holding? Find out from your onchain history.',
    url: APP_URL,
    siteName: 'DeFier',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'DeFier',
    description: 'Did providing liquidity actually beat holding?',
  },
  other: {
    // Base App reads this to render the app as an embed rather than a plain link.
    'fc:miniapp': JSON.stringify({
      version: '1',
      imageUrl: `${APP_URL}/og.png`,
      button: {
        title: 'Analyse a wallet',
        action: { type: 'launch_miniapp', name: 'DeFier', url: APP_URL, splashBackgroundColor: '#08090C' },
      },
    }),
  },
};
export const viewport: Viewport = { width: 'device-width', initialScale: 1, maximumScale: 5, themeColor: '#08090C' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* OnchainKit ships Tailwind v4 CSS; loading it as a plain stylesheet keeps it
            out of our Tailwind v3 pipeline. Generated by scripts/copy-onchainkit-styles.mjs. */}
        <link rel="stylesheet" href="/onchainkit.css" />
      </head>
      <body>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
