import type { Metadata, Viewport } from 'next';
import '../styles/globals.css';
import { Providers } from '@/components/Providers';
import { AppShell } from '@/components/AppShell';

export const metadata: Metadata = {
  title: 'DeFier · Know what your capital is actually earning',
  description: 'Onchain capital intelligence on Base. True LP P&L, LP vs HODL, exposure, tokenized stocks and an AI that explains it.',
  // TODO(Part 4): Mini App metadata (fc:frame / fc:miniapp) per docs.base.org/mini-apps
};
export const viewport: Viewport = { width: 'device-width', initialScale: 1, themeColor: '#FAFAF9' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* OnchainKit ships Tailwind v4 CSS; loading it as a plain stylesheet keeps it
            out of our Tailwind v3 pipeline. Generated by scripts/copy-onchainkit-styles.mjs. */}
        <link rel="stylesheet" href="/onchainkit.css" />
      </head>
      <body>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
